### ISSUE TITLE
[BUG修复]在线网址无法使用

### ISSUE THREAD

**Issue by mio4** [zerosoul/github-star-stats#5]
https://api.github.com/graphql  请求挂掉

**Comment by zerosoul** [comment]
> https://api.github.com/graphql 请求挂掉

刚刚我试了下 能正常使用 如果你那儿还不行的话 可以加我vx：yanggc_2013 了解下情况

**Comment by mio4** [comment]
![image](https://user-images.githubusercontent.com/22285655/93671085-b67ddf00-fad2-11ea-8e38-bab77c42f2a5.png)

看起来是因为IP请求频率过高？

**Comment by zerosoul** [comment]
> ![image](https://user-images.githubusercontent.com/22285655/93671085-b67ddf00-fad2-11ea-8e38-bab77c42f2a5.png)
> 
> 看起来是因为IP请求频率过高？

看提示是这个意思，有时间我把这种情况捕捉处理下，给出友好提示~
