### ISSUE TITLE
提示Github API Unauthorized!

### ISSUE THREAD

**Issue by GT-ZhangAcer** [zerosoul/github-star-stats#7]
今天用的时候点击Awesome后提示Github API Unauthorized!（不知道是不是我这边的问题）
<img width="1019" alt="图片" src="https://user-images.githubusercontent.com/46156734/104307773-a28b3c80-550a-11eb-8266-3c550fe88b6a.png">

感觉这是最好用的查⭐工具了，今天突然不能用找了好几个高⭐的查星工具，但还是感觉这个是最好用的~

**Comment by richard1015** [comment]
马上跟进

**Comment by zerosoul** [comment]
> 今天用的时候点击Awesome后提示Github API Unauthorized!（不知道是不是我这边的问题）
> <img alt="图片" width="1019" src="https://user-images.githubusercontent.com/46156734/104307773-a28b3c80-550a-11eb-8266-3c550fe88b6a.png">
> 
> 感觉这是最好用的查⭐工具了，今天突然不能用找了好几个高⭐的查星工具，但还是感觉这个是最好用的~

不好意思，前两天确实出了点问题，当天就修复了，现在应该是好了。

**Comment by GT-ZhangAcer** [comment]
> > 今天用的时候点击Awesome后提示Github API Unauthorized!（不知道是不是我这边的问题）
> > <img alt="图片" width="1019" src="https://user-images.githubusercontent.com/46156734/104307773-a28b3c80-550a-11eb-8266-3c550fe88b6a.png">
> > 感觉这是最好用的查⭐工具了，今天突然不能用找了好几个高⭐的查星工具，但还是感觉这个是最好用的~
> 
> 不好意思，前两天确实出了点问题，当天就修复了，现在应该是好了。

太感谢大佬啦~东西实在是好用
